name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/NISTtheDocs2Death@main
        with:
          docs-folder: docs/
          pre-build-command: "apt-get update -y && apt-get install -y pandoc"
          build-command: sphinx-build -b html -c . source _build/html
