name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/NISTtheDocs2Death@main
        with:
          docs-folder: docs/
          build-command: sphinx-build -b html -n -c . source _build/html/
